export default [
  {
    id: 494363832,
    node_id: "R_kgDOHXdkuA",
    name: "WE",
    full_name: "AtharvaAshar/WE",
    private: false,
    owner: {
      login: "AtharvaAshar",
      id: 102160142,
      node_id: "U_kgDOBhbXDg",
      avatar_url: "https://avatars.githubusercontent.com/u/102160142?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/AtharvaAshar",
      html_url: "https://github.com/AtharvaAshar",
      followers_url: "https://api.github.com/users/AtharvaAshar/followers",
      following_url:
        "https://api.github.com/users/AtharvaAshar/following{/other_user}",
      gists_url: "https://api.github.com/users/AtharvaAshar/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/AtharvaAshar/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/AtharvaAshar/subscriptions",
      organizations_url: "https://api.github.com/users/AtharvaAshar/orgs",
      repos_url: "https://api.github.com/users/AtharvaAshar/repos",
      events_url: "https://api.github.com/users/AtharvaAshar/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/AtharvaAshar/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/AtharvaAshar/WE",
    description: null,
    fork: false,
    url: "https://api.github.com/repos/AtharvaAshar/WE",
    forks_url: "https://api.github.com/repos/AtharvaAshar/WE/forks",
    keys_url: "https://api.github.com/repos/AtharvaAshar/WE/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/AtharvaAshar/WE/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/AtharvaAshar/WE/teams",
    hooks_url: "https://api.github.com/repos/AtharvaAshar/WE/hooks",
    issue_events_url:
      "https://api.github.com/repos/AtharvaAshar/WE/issues/events{/number}",
    events_url: "https://api.github.com/repos/AtharvaAshar/WE/events",
    assignees_url:
      "https://api.github.com/repos/AtharvaAshar/WE/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/AtharvaAshar/WE/branches{/branch}",
    tags_url: "https://api.github.com/repos/AtharvaAshar/WE/tags",
    blobs_url: "https://api.github.com/repos/AtharvaAshar/WE/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/AtharvaAshar/WE/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/AtharvaAshar/WE/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/AtharvaAshar/WE/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/AtharvaAshar/WE/statuses/{sha}",
    languages_url: "https://api.github.com/repos/AtharvaAshar/WE/languages",
    stargazers_url: "https://api.github.com/repos/AtharvaAshar/WE/stargazers",
    contributors_url:
      "https://api.github.com/repos/AtharvaAshar/WE/contributors",
    subscribers_url: "https://api.github.com/repos/AtharvaAshar/WE/subscribers",
    subscription_url:
      "https://api.github.com/repos/AtharvaAshar/WE/subscription",
    commits_url: "https://api.github.com/repos/AtharvaAshar/WE/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/AtharvaAshar/WE/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/AtharvaAshar/WE/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/AtharvaAshar/WE/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/AtharvaAshar/WE/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/AtharvaAshar/WE/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/AtharvaAshar/WE/merges",
    archive_url:
      "https://api.github.com/repos/AtharvaAshar/WE/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/AtharvaAshar/WE/downloads",
    issues_url: "https://api.github.com/repos/AtharvaAshar/WE/issues{/number}",
    pulls_url: "https://api.github.com/repos/AtharvaAshar/WE/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/AtharvaAshar/WE/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/AtharvaAshar/WE/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/AtharvaAshar/WE/labels{/name}",
    releases_url: "https://api.github.com/repos/AtharvaAshar/WE/releases{/id}",
    deployments_url: "https://api.github.com/repos/AtharvaAshar/WE/deployments",
    created_at: "2022-05-20T07:25:27Z",
    updated_at: "2022-06-21T17:26:04Z",
    pushed_at: "2022-05-20T07:38:50Z",
    git_url: "git://github.com/AtharvaAshar/WE.git",
    ssh_url: "git@github.com:AtharvaAshar/WE.git",
    clone_url: "https://github.com/AtharvaAshar/WE.git",
    svn_url: "https://github.com/AtharvaAshar/WE",
    homepage: null,
    size: 1319,
    stargazers_count: 1,
    watchers_count: 1,
    language: "javascript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: "master",
  },
  {
    id: 494363831,
    node_id: "R_kgDOHXdkuA",
    name: "WE",
    full_name: "AtharvaAshar/WE",
    private: false,
    owner: {
      login: "AtharvaAshar",
      id: 102160142,
      node_id: "U_kgDOBhbXDg",
      avatar_url: "https://avatars.githubusercontent.com/u/102160142?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/AtharvaAshar",
      html_url: "https://github.com/AtharvaAshar",
      followers_url: "https://api.github.com/users/AtharvaAshar/followers",
      following_url:
        "https://api.github.com/users/AtharvaAshar/following{/other_user}",
      gists_url: "https://api.github.com/users/AtharvaAshar/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/AtharvaAshar/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/AtharvaAshar/subscriptions",
      organizations_url: "https://api.github.com/users/AtharvaAshar/orgs",
      repos_url: "https://api.github.com/users/AtharvaAshar/repos",
      events_url: "https://api.github.com/users/AtharvaAshar/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/AtharvaAshar/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/AtharvaAshar/WE",
    description: null,
    fork: false,
    url: "https://api.github.com/repos/AtharvaAshar/WE",
    forks_url: "https://api.github.com/repos/AtharvaAshar/WE/forks",
    keys_url: "https://api.github.com/repos/AtharvaAshar/WE/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/AtharvaAshar/WE/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/AtharvaAshar/WE/teams",
    hooks_url: "https://api.github.com/repos/AtharvaAshar/WE/hooks",
    issue_events_url:
      "https://api.github.com/repos/AtharvaAshar/WE/issues/events{/number}",
    events_url: "https://api.github.com/repos/AtharvaAshar/WE/events",
    assignees_url:
      "https://api.github.com/repos/AtharvaAshar/WE/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/AtharvaAshar/WE/branches{/branch}",
    tags_url: "https://api.github.com/repos/AtharvaAshar/WE/tags",
    blobs_url: "https://api.github.com/repos/AtharvaAshar/WE/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/AtharvaAshar/WE/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/AtharvaAshar/WE/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/AtharvaAshar/WE/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/AtharvaAshar/WE/statuses/{sha}",
    languages_url: "https://api.github.com/repos/AtharvaAshar/WE/languages",
    stargazers_url: "https://api.github.com/repos/AtharvaAshar/WE/stargazers",
    contributors_url:
      "https://api.github.com/repos/AtharvaAshar/WE/contributors",
    subscribers_url: "https://api.github.com/repos/AtharvaAshar/WE/subscribers",
    subscription_url:
      "https://api.github.com/repos/AtharvaAshar/WE/subscription",
    commits_url: "https://api.github.com/repos/AtharvaAshar/WE/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/AtharvaAshar/WE/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/AtharvaAshar/WE/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/AtharvaAshar/WE/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/AtharvaAshar/WE/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/AtharvaAshar/WE/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/AtharvaAshar/WE/merges",
    archive_url:
      "https://api.github.com/repos/AtharvaAshar/WE/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/AtharvaAshar/WE/downloads",
    issues_url: "https://api.github.com/repos/AtharvaAshar/WE/issues{/number}",
    pulls_url: "https://api.github.com/repos/AtharvaAshar/WE/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/AtharvaAshar/WE/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/AtharvaAshar/WE/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/AtharvaAshar/WE/labels{/name}",
    releases_url: "https://api.github.com/repos/AtharvaAshar/WE/releases{/id}",
    deployments_url: "https://api.github.com/repos/AtharvaAshar/WE/deployments",
    created_at: "2022-05-20T07:25:27Z",
    updated_at: "2022-06-21T17:26:04Z",
    pushed_at: "2022-05-20T07:38:50Z",
    git_url: "git://github.com/AtharvaAshar/WE.git",
    ssh_url: "git@github.com:AtharvaAshar/WE.git",
    clone_url: "https://github.com/AtharvaAshar/WE.git",
    svn_url: "https://github.com/AtharvaAshar/WE",
    homepage: null,
    size: 1319,
    stargazers_count: 1,
    watchers_count: 1,
    language: "javascript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: "master",
  },
];
