export default {
  login: "AtharvaAshar",
  id: 102160142,
  node_id: "U_kgDOBhbXDg",
  avatar_url: "https://avatars.githubusercontent.com/u/102160142?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AtharvaAshar",
  html_url: "https://github.com/AtharvaAshar",
  followers_url: "https://api.github.com/users/AtharvaAshar/followers",
  following_url:
    "https://api.github.com/users/AtharvaAshar/following{/other_user}",
  gists_url: "https://api.github.com/users/AtharvaAshar/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/AtharvaAshar/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AtharvaAshar/subscriptions",
  organizations_url: "https://api.github.com/users/AtharvaAshar/orgs",
  repos_url: "https://api.github.com/users/AtharvaAshar/repos",
  events_url: "https://api.github.com/users/AtharvaAshar/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/AtharvaAshar/received_events",
  type: "User",
  site_admin: false,
  name: "Atharva Ashar",
  company: null,
  blog: "",
  location: "Thane",
  email: null,
  hireable: null,
  bio: null,
  twitter_usernam: null,
  public_repos: 1,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: "2022-03-22T12:55:41Z",
  updated_at: "2022-08-31T11:58:06Z",
};
